interval_minutes: 5

urls:
  - https://www.google.es
  - https://tssciberseguridad.com/
  - https://www.github.com
  - https://www.wikipedia.org
  - https://httpbin.org/status/404
  - https://httpbin.org/status/500
  - https://httpbin.org/status/503

timeout_seconds: 5
latency_warning_ms: 1000
latency_critical_ms: 3000
